export const authContent = {
  en: {
    home: 'Home',
    signIn: 'Sign in',
    register: 'Create account',
    profile: 'Profile',
    admin: 'User directory',
    signOut: 'Sign out',
    accountEyebrow: 'SECURE ACCESS / PHASE 02',
    loginTitle: 'Welcome back.',
    loginDescription: 'Use your DECI.Project account to continue securely.',
    registerTitle: 'Create your account.',
    registerDescription: 'Register as a customer and receive protected access to your profile and cart.',
    name: 'Full name',
    email: 'Email address',
    password: 'Password',
    phone: 'Phone (optional)',
    address: 'Address (optional)',
    currentPassword: 'Current password',
    newPassword: 'New password',
    save: 'Save changes',
    changePassword: 'Change password',
    submitLogin: 'Sign in securely',
    submitRegister: 'Create customer account',
    processing: 'Processing…',
    haveAccount: 'Already have an account?',
    needAccount: 'New to DECI.Project?',
    profileTitle: 'Your account profile',
    profileDescription: 'View and update the personal information connected to your authenticated account.',
    role: 'Account role',
    active: 'Active',
    status: 'Status',
    adminTitle: 'Registered users',
    adminDescription: 'This route and API are restricted to Admin accounts.',
    forbiddenTitle: 'Admin access required',
    forbiddenDescription: 'Your Customer account is authenticated, but it does not have permission to view this area.',
    loadingSession: 'Restoring your secure session…',
    authRequired: 'You need to sign in before opening this page.',
    successProfile: 'Profile updated successfully.',
    successPassword: 'Password changed. Previous sessions are now invalid.',
    emptyUsers: 'No users were returned.',
    userName: 'Name', userEmail: 'Email', userRole: 'Role', userStatus: 'Status', userCreated: 'Created', enabled: 'Active', disabled: 'Disabled',
  },
  ar: {
    home: 'الرئيسية',
    signIn: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    profile: 'الملف الشخصي',
    admin: 'دليل المستخدمين',
    signOut: 'تسجيل الخروج',
    accountEyebrow: 'وصول آمن / المرحلة 02',
    loginTitle: 'مرحبًا بعودتك.',
    loginDescription: 'استخدم حساب DECI.Project للمتابعة بأمان.',
    registerTitle: 'أنشئ حسابك.',
    registerDescription: 'سجّل كعميل واحصل على وصول محمي إلى ملفك الشخصي وسلة التسوق.',
    name: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    phone: 'الهاتف (اختياري)',
    address: 'العنوان (اختياري)',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    save: 'حفظ التغييرات',
    changePassword: 'تغيير كلمة المرور',
    submitLogin: 'تسجيل الدخول بأمان',
    submitRegister: 'إنشاء حساب عميل',
    processing: 'جارٍ التنفيذ…',
    haveAccount: 'لديك حساب بالفعل؟',
    needAccount: 'جديد في DECI.Project؟',
    profileTitle: 'ملف حسابك',
    profileDescription: 'اعرض وحدّث البيانات الشخصية المرتبطة بحسابك الموثق.',
    role: 'دور الحساب',
    active: 'نشط',
    status: 'الحالة',
    adminTitle: 'المستخدمون المسجلون',
    adminDescription: 'هذه الصفحة والواجهة البرمجية متاحتان لحسابات الإدارة فقط.',
    forbiddenTitle: 'يتطلب صلاحية مدير',
    forbiddenDescription: 'حساب العميل موثق، لكنه لا يملك صلاحية عرض هذه المنطقة.',
    loadingSession: 'جارٍ استعادة جلستك الآمنة…',
    authRequired: 'يجب تسجيل الدخول قبل فتح هذه الصفحة.',
    successProfile: 'تم تحديث الملف الشخصي بنجاح.',
    successPassword: 'تم تغيير كلمة المرور وإلغاء الجلسات السابقة.',
    emptyUsers: 'لم يتم العثور على مستخدمين.',
    userName: 'الاسم', userEmail: 'البريد الإلكتروني', userRole: 'الدور', userStatus: 'الحالة', userCreated: 'تاريخ الإنشاء', enabled: 'نشط', disabled: 'معطل',
  },
};
