export const commerceContent = {
  en: {
    products: 'Products', cart: 'Cart', orders: 'Orders', dashboard: 'Dashboard', adminCatalog: 'Catalog',
    homeEyebrow: 'CURATED ELECTRONICS / CAIRO', homeTitle: 'Technology that fits real life.',
    homeDescription: 'Discover dependable electronics, clear specifications, and a checkout experience built for confidence.',
    shopNow: 'Shop the catalog', exploreCategories: 'Explore categories', liveCatalog: 'Live catalog',
    homeFeatured: 'Featured this week', homeFeaturedDescription: 'Live products selected from the store API.',
    homeCategories: 'Shop by category', homeCategoriesDescription: 'Browse the latest devices by the way you use them.',
    homePromise: 'Why ShopSphere', promiseOneTitle: 'Clear choices', promiseOneText: 'Useful specifications, stock visibility, and transparent EGP pricing.',
    promiseTwoTitle: 'Secure account', promiseTwoText: 'Protected authentication, private profiles, and server-side carts.',
    promiseThreeTitle: 'Simple checkout', promiseThreeText: 'A reviewable simulated checkout that creates a real order record.',
    promotionTitle: 'Build your everyday setup.', promotionText: 'Combine laptops, audio, gaming, and accessories in one persistent cart.',
    promotionAction: 'Browse all products', catalogCount: 'products available', categoryCount: 'categories', secureCheckout: 'secure account checkout',
    discoveryEyebrow: 'ELECTRONICS CATALOG / LIVE API', discoveryTitle: 'Find your next device.',
    discoveryDescription: 'Search, filter, sort, and browse products loaded directly from the ShopSphere backend.',
    search: 'Search products', allCategories: 'All categories', newest: 'Newest', oldest: 'Oldest', priceLow: 'Price: low to high', priceHigh: 'Price: high to low',
    nameAZ: 'Name: A–Z', nameZA: 'Name: Z–A', brand: 'Brand', minPrice: 'Minimum price', maxPrice: 'Maximum price', featuredOnly: 'Featured only',
    clearFilters: 'Clear filters', results: 'results', noProducts: 'No products match these filters.', noProductsHelp: 'Try a different search or remove one of the filters.',
    viewDetails: 'View details', featured: 'Featured', inStock: 'in stock', outOfStock: 'Out of stock',
    loading: 'Loading products…', loadingDescription: 'The latest catalog data is being requested from the backend.', loadError: 'Products could not be loaded.', categoryLoading: 'Loading categories…', categoryLoadError: 'Categories could not be loaded.',
    retry: 'Try again', previous: 'Previous', next: 'Next', page: 'Page', of: 'of',
    addToCart: 'Add to cart', addedToCart: 'Added to your cart.', adding: 'Adding…', quantity: 'Quantity', increaseQuantity: 'Increase quantity', decreaseQuantity: 'Decrease quantity', backProducts: 'Back to products', productMissing: 'Product not found.',
    productMissingHelp: 'The product may have been removed or the link may be incorrect.', specifications: 'Product overview', stockAvailable: 'Available stock', securePurchase: 'Authenticated cart and simulated checkout',
    cartTitle: 'Your shopping cart', cartDescription: 'Change quantities, remove items, and verify totals before simulated checkout.', emptyCart: 'Your cart is empty.',
    emptyCartHelp: 'Products you add will remain connected to your account.', continueShopping: 'Continue shopping', remove: 'Remove', update: 'Update', subtotal: 'Subtotal', total: 'Total',
    checkout: 'Shipping and simulated checkout', placeOrder: 'Place simulated order', fullName: 'Full name', phone: 'Phone', addressLine: 'Street address', city: 'City',
    governorate: 'Governorate', postalCode: 'Postal code', orderSuccess: 'Order created successfully.', checkoutNotice: 'No real payment will be charged.',
    orderHistory: 'Order history', orderHistoryDescription: 'Review orders created by your authenticated account.', orderNumber: 'Order', orderDate: 'Placed', orderStatus: 'Status', orderItems: 'items',
    noOrders: 'No orders yet.', noOrdersHelp: 'Your completed simulated checkouts will appear here.',
    adminDashboard: 'Admin dashboard', adminDashboardTitle: 'Store operations at a glance.', adminDashboardDescription: 'Live catalog and account information from protected APIs.',
    totalProducts: 'Products', totalCategories: 'Categories', totalUsers: 'Users', lowStock: 'Low stock', recentProducts: 'Recent products', adminActions: 'Management areas',
    manageCatalog: 'Manage catalog', manageCatalogText: 'Create, update, delete, and illustrate products and categories.', manageUsers: 'Review users', manageUsersText: 'Inspect registered Customer and Admin accounts.',
    adminTitle: 'Catalog management', adminDescription: 'Create and maintain categories, products, inventory, and product images.',
    categories: 'Categories', categoryName: 'Category name', categoryDescription: 'Category description', createCategory: 'Create category', updateCategory: 'Update category', deleteCategory: 'Delete category',
    productName: 'Product name', sku: 'SKU', description: 'Description', price: 'Price (EGP)', stock: 'Stock', category: 'Category', featuredProduct: 'Featured product',
    createProduct: 'Create product', uploadImages: 'Upload images', currentImages: 'Current images', deleteImage: 'Remove image', saveProduct: 'Save product', deleteProduct: 'Delete', editProduct: 'Edit', cancel: 'Cancel',
    adminEmpty: 'Create a category and product to begin.', saveSuccess: 'Changes saved successfully.', imageUploadPartialSuccess: 'Product saved successfully, but its images could not be uploaded. Open the product editor to retry the image upload.', confirmDeleteProduct: 'Delete this product permanently?', confirmDeleteCategory: 'Delete this empty category?',
    loadingDashboard: 'Loading dashboard…', dashboardError: 'Dashboard data could not be loaded.', navigation: 'Navigation', openMenu: 'Open navigation menu', closeMenu: 'Close navigation menu',
  },
  ar: {
    products: 'المنتجات', cart: 'السلة', orders: 'الطلبات', dashboard: 'لوحة التحكم', adminCatalog: 'الكتالوج',
    homeEyebrow: 'إلكترونيات مختارة / القاهرة', homeTitle: 'تقنية تناسب حياتك اليومية.',
    homeDescription: 'اكتشف إلكترونيات موثوقة ومواصفات واضحة وتجربة طلب مصممة بثقة.',
    shopNow: 'تصفح الكتالوج', exploreCategories: 'استكشف الفئات', liveCatalog: 'كتالوج مباشر',
    homeFeatured: 'مختارات هذا الأسبوع', homeFeaturedDescription: 'منتجات حية مختارة من واجهة المتجر البرمجية.',
    homeCategories: 'تسوق حسب الفئة', homeCategoriesDescription: 'تصفح أحدث الأجهزة بالطريقة التي تستخدمها بها.',
    homePromise: 'لماذا ShopSphere', promiseOneTitle: 'اختيارات واضحة', promiseOneText: 'مواصفات مفيدة ومخزون ظاهر وأسعار واضحة بالجنيه المصري.',
    promiseTwoTitle: 'حساب آمن', promiseTwoText: 'مصادقة محمية وملف خاص وسلة محفوظة على الخادم.',
    promiseThreeTitle: 'طلب بسيط', promiseThreeText: 'دفع تجريبي قابل للمراجعة ينشئ سجل طلب حقيقيًا.',
    promotionTitle: 'كوّن تجهيزتك اليومية.', promotionText: 'اجمع الحواسيب والصوتيات والألعاب والإكسسوارات في سلة واحدة محفوظة.',
    promotionAction: 'تصفح كل المنتجات', catalogCount: 'منتج متاح', categoryCount: 'فئات', secureCheckout: 'دفع بحساب آمن',
    discoveryEyebrow: 'كتالوج الإلكترونيات / واجهة حية', discoveryTitle: 'اعثر على جهازك القادم.',
    discoveryDescription: 'ابحث وصفِّ ورتّب وتصفح المنتجات المحملة مباشرة من خادم ShopSphere.',
    search: 'ابحث عن المنتجات', allCategories: 'كل الفئات', newest: 'الأحدث', oldest: 'الأقدم', priceLow: 'السعر: من الأقل', priceHigh: 'السعر: من الأعلى',
    nameAZ: 'الاسم: أ–ي', nameZA: 'الاسم: ي–أ', brand: 'العلامة التجارية', minPrice: 'أقل سعر', maxPrice: 'أعلى سعر', featuredOnly: 'المنتجات المميزة فقط',
    clearFilters: 'مسح المرشحات', results: 'نتيجة', noProducts: 'لا توجد منتجات مطابقة.', noProductsHelp: 'جرّب بحثًا مختلفًا أو أزل أحد المرشحات.',
    viewDetails: 'عرض التفاصيل', featured: 'مميز', inStock: 'متوفر', outOfStock: 'غير متوفر',
    loading: 'جارٍ تحميل المنتجات…', loadingDescription: 'يتم طلب أحدث بيانات الكتالوج من الخادم.', loadError: 'تعذر تحميل المنتجات.', categoryLoading: 'جارٍ تحميل الفئات…', categoryLoadError: 'تعذر تحميل الفئات.',
    retry: 'حاول مرة أخرى', previous: 'السابق', next: 'التالي', page: 'صفحة', of: 'من',
    addToCart: 'أضف إلى السلة', addedToCart: 'تمت الإضافة إلى سلتك.', adding: 'جارٍ الإضافة…', quantity: 'الكمية', increaseQuantity: 'زيادة الكمية', decreaseQuantity: 'تقليل الكمية', backProducts: 'العودة للمنتجات', productMissing: 'المنتج غير موجود.',
    productMissingHelp: 'قد يكون المنتج قد حُذف أو أن الرابط غير صحيح.', specifications: 'نظرة عامة على المنتج', stockAvailable: 'المخزون المتاح', securePurchase: 'سلة موثقة ودفع تجريبي',
    cartTitle: 'سلة التسوق', cartDescription: 'غيّر الكميات واحذف المنتجات وتحقق من الإجمالي قبل الدفع التجريبي.', emptyCart: 'سلة التسوق فارغة.',
    emptyCartHelp: 'ستظل المنتجات التي تضيفها مرتبطة بحسابك.', continueShopping: 'متابعة التسوق', remove: 'حذف', update: 'تحديث', subtotal: 'المجموع الفرعي', total: 'الإجمالي',
    checkout: 'الشحن والدفع التجريبي', placeOrder: 'إنشاء طلب تجريبي', fullName: 'الاسم الكامل', phone: 'الهاتف', addressLine: 'عنوان الشارع', city: 'المدينة',
    governorate: 'المحافظة', postalCode: 'الرمز البريدي', orderSuccess: 'تم إنشاء الطلب بنجاح.', checkoutNotice: 'لن يتم خصم أي مبلغ حقيقي.',
    orderHistory: 'سجل الطلبات', orderHistoryDescription: 'راجع الطلبات التي أنشأها حسابك الموثق.', orderNumber: 'الطلب', orderDate: 'تاريخ الإنشاء', orderStatus: 'الحالة', orderItems: 'منتج',
    noOrders: 'لا توجد طلبات بعد.', noOrdersHelp: 'ستظهر هنا عمليات الدفع التجريبية المكتملة.',
    adminDashboard: 'لوحة تحكم الإدارة', adminDashboardTitle: 'عمليات المتجر في لمحة.', adminDashboardDescription: 'بيانات حية للكتالوج والحسابات من واجهات محمية.',
    totalProducts: 'المنتجات', totalCategories: 'الفئات', totalUsers: 'المستخدمون', lowStock: 'مخزون منخفض', recentProducts: 'أحدث المنتجات', adminActions: 'مناطق الإدارة',
    manageCatalog: 'إدارة الكتالوج', manageCatalogText: 'أنشئ وحدّث واحذف المنتجات والفئات وأضف الصور.', manageUsers: 'مراجعة المستخدمين', manageUsersText: 'افحص حسابات العملاء والمديرين المسجلة.',
    adminTitle: 'إدارة الكتالوج', adminDescription: 'أنشئ وحافظ على الفئات والمنتجات والمخزون وصور المنتجات.',
    categories: 'الفئات', categoryName: 'اسم الفئة', categoryDescription: 'وصف الفئة', createCategory: 'إنشاء فئة', updateCategory: 'تحديث الفئة', deleteCategory: 'حذف الفئة',
    productName: 'اسم المنتج', sku: 'رمز المنتج', description: 'الوصف', price: 'السعر (جنيه)', stock: 'المخزون', category: 'الفئة', featuredProduct: 'منتج مميز',
    createProduct: 'إنشاء المنتج', uploadImages: 'رفع الصور', currentImages: 'الصور الحالية', deleteImage: 'إزالة الصورة', saveProduct: 'حفظ المنتج', deleteProduct: 'حذف', editProduct: 'تعديل', cancel: 'إلغاء',
    adminEmpty: 'أنشئ فئة ومنتجًا للبدء.', saveSuccess: 'تم حفظ التغييرات.', imageUploadPartialSuccess: 'تم حفظ المنتج بنجاح، لكن تعذر رفع صوره. افتح محرر المنتج لإعادة محاولة رفع الصور.', confirmDeleteProduct: 'هل تريد حذف هذا المنتج نهائيًا؟', confirmDeleteCategory: 'هل تريد حذف هذه الفئة الفارغة؟',
    loadingDashboard: 'جارٍ تحميل لوحة التحكم…', dashboardError: 'تعذر تحميل بيانات لوحة التحكم.', navigation: 'التنقل', openMenu: 'فتح قائمة التنقل', closeMenu: 'إغلاق قائمة التنقل',
  },
};
