export const foundationContent = {
  en: {
    eyebrow: 'FULL-STACK ELECTRONICS COMMERCE',
    title: 'A dependable foundation for every shopping experience.',
    description:
      'ShopSphere connects a React storefront to an Express API, PostgreSQL through Prisma, and MongoDB for flexible services.',
    phase: 'Phase 2 · Secure accounts ready',
    live: 'Live system status',
    apiOnline: 'API process online',
    apiOffline: 'API not reachable',
    checking: 'Checking backend…',
    openHealth: 'Open API health check',
    architecture: 'System architecture',
    stack: [
      { name: 'React Frontend', detail: 'Responsive bilingual interface with light and dark modes.' },
      { name: 'Express API', detail: 'Secure modular backend with validation and health endpoints.' },
      { name: 'PostgreSQL + Prisma', detail: 'Relational users, products, carts, and orders.' },
      { name: 'MongoDB', detail: 'Product reviews and auditable activity logs.' },
    ],
    next: 'Next implementation phase',
    nextText: 'Product CRUD, categories, search, cart, image uploads, orders, and simulated checkout.',
    language: 'العربية',
    themeLight: 'Light',
    themeDark: 'Dark',
  },
  ar: {
    eyebrow: 'متجر إلكترونيات متكامل',
    title: 'أساس موثوق لكل تجربة تسوق.',
    description:
      'يربط مشروع ShopSphere واجهة React بواجهة Express وقاعدة PostgreSQL من خلال Prisma وMongoDB للخدمات المرنة.',
    phase: 'المرحلة الثانية · الحسابات الآمنة جاهزة',
    live: 'حالة النظام المباشرة',
    apiOnline: 'واجهة الخادم تعمل',
    apiOffline: 'تعذر الوصول إلى الخادم',
    checking: 'جارٍ فحص الخادم…',
    openHealth: 'فتح فحص صحة الخادم',
    architecture: 'بنية النظام',
    stack: [
      { name: 'واجهة React', detail: 'واجهة متجاوبة باللغتين مع الوضعين الفاتح والداكن.' },
      { name: 'واجهة Express', detail: 'خادم آمن ومنظم مع التحقق ومسارات فحص الصحة.' },
      { name: 'PostgreSQL + Prisma', detail: 'بيانات مترابطة للمستخدمين والمنتجات والسلال والطلبات.' },
      { name: 'MongoDB', detail: 'مراجعات المنتجات وسجلات النشاط القابلة للتدقيق.' },
    ],
    next: 'مرحلة التنفيذ التالية',
    nextText: 'إدارة المنتجات والفئات والبحث والسلة والصور والطلبات والدفع التجريبي.',
    language: 'English',
    themeLight: 'فاتح',
    themeDark: 'داكن',
  },
};
